import nltk
from nltk.chat.util import Chat, reflections
from sys import version_info
from string import punctuation
from nltk.corpus import stopwords
from nltk.tokenize import word_tokenize
from nltk.stem import PorterStemmer, WordNetLemmatizer

pairs = [
    [
        r"How can I avail internet reservation facility through credit cards?",
        [
            'Recently internet reservation facility has started on Indian Railways. The web site http://www.irctc.co.in is operational, wherein you can get the railway reservation done through Credit Cards.For more on Reservation through credit cards click here  Internet Reservation', ]
    ],
    [
        r'Why are PNR and reservation availability queries not available after certain timings at night?',
        [
            'The online PNR and seat availability queries are fetched from the computerized reservation applications. These online reservation applications are shut down daily around 2330 hrs to 0030 hrs IST. Due to the dynamic changes taking place in the PNR status updation and the availability positions, these two types of queries have to be fetched from the online reservation applications, hence the non- availability of them after certain timings. The sheer size of these databases does not allow them to be copied over network lines.Please note that the web site is functional 24 hrs. a day and other queries (trains between any two stations, fare queries, etc.) are functional throughout the day.', ]
    ],
    [
        r'How can I avail the enquiries, through SMS on mobile phones?',
        [
            'Now all the enquiries offered on the web site www.indianrail.gov.in are available on your mobile phone through SMS facility. For more information on the mobile service providers and the key words to be used on the mobile, please click here, SMS help . Please note that we are giving the backend service only for the SMS queries. For more information and help on key words and SMS facility, kindly contact the mobile service provider according to the table.', ]
    ],
    [
        r'Why do sometimes the fonts, colors schemes and java scripts behave differently in some browser or browsers?',
        [
            'This web site is best viewed with Microsoft Internet Explorer 6.0 and above. It might not give desired results with other browsers. All the pages, color schemes and scripts have been tested for IE 6.0 and above. ', ]
    ],
    [
        r'Where can I get the latest arrival and departure timings of trains, when they get delayed?',
        [
            'The latest arrival and departure timings of delayed trains, alongwith diverted routes etc. will be made available shortly on this web site only.', ]
    ],
    [
        r'Where can I lodge complaint against any type of grievances in the Trains, Platforms, officials for problems on this web site and give suggestions?',
        [
            'The complaint software is presently under development. We try our best to forward your grievances to the concerned department. However please note that this is not always possible. Please note that all your complaints and suggestions for the improvement of the web site http://www.indianrail.gov.in  can be put on the Feedback & suggestions page. Please note that, in case of any problems, give the query type (hyper link), the inputs which you gave, and the exact error message generated by this web site. All this will help us in solving the problems quickly. In the absence of such inputs, we cannot solve the problems.', ]
    ],
]


def unique(list1):
    unique_list = []
    for x in list1:
        if x not in unique_list:
            unique_list.append(x)
    return unique_list


lemmatiser = WordNetLemmatizer()


def preprocessing(sent):
    rem_words = ['get', 'avail', 'who', 'where', 'how', 'what', 'why', 'when', 'I', 'can']
    for p in list(punctuation):
        sent = sent.replace(p, '')
    sent = sent.lower().split()
    # remove stop words
    stop_words = set(stopwords.words('english'))
    sent = [i for i in sent if not i in stop_words]
    sent = [i for i in sent if not i in rem_words]
    sent = [lemmatiser.lemmatize(item, pos="v") for item in sent]
    return unique(sent)


def tellme_bot():
    while 1:
        response = input("Tell Me. [q to quit]>")
        if response == 'q':
            break
        i = 0
        chosen = len(pairs)
        matches = 0
        list_response = preprocessing(response)
        while i < len(pairs):
            loc_matches = 0
            x = pairs[i][0] + "  ".join(pairs[i][1])
            list_pair = preprocessing(x)
            for word in list_pair:
                if word in list_response:
                    loc_matches = loc_matches + 1
            if loc_matches > matches:
                chosen = i
                matches = loc_matches
            i = i + 1
        if chosen < len(pairs):
            ans = pairs[chosen][1]
            print(ans[0])
        else:
            print("Unable to answer this question")
        break

tellme_bot()